
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.robertob.p1compi2.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RW_REAL = 40;
  public static final int ARROW = 85;
  public static final int RW_BOOLEAN = 43;
  public static final int RW_TYPE = 32;
  public static final int RW_STRING = 42;
  public static final int RW_WHILE = 35;
  public static final int RW_NOT = 21;
  public static final int DOUBLEASTERISK = 64;
  public static final int RW_NIL = 20;
  public static final int RW_VAR = 34;
  public static final int UNIT_MINUS = 50;
  public static final int COMMA = 79;
  public static final int RW_BREAK = 46;
  public static final int RW_PACKED = 24;
  public static final int INTEGER = 53;
  public static final int RW_MOD = 19;
  public static final int RW_WRITELN = 48;
  public static final int NOT = 78;
  public static final int CLOSEBRACE = 60;
  public static final int RW_LABEL = 18;
  public static final int RW_THEN = 30;
  public static final int RW_GOTO = 15;
  public static final int RW_AND_THEN = 44;
  public static final int LTGT = 73;
  public static final int RW_DO = 8;
  public static final int RW_FOR = 13;
  public static final int RW_DIV = 7;
  public static final int MODULO = 63;
  public static final int SLASH = 62;
  public static final int RW_PROGRAM = 26;
  public static final int RW_TRUE = 37;
  public static final int DOUBLEEQUALS = 67;
  public static final int LESSEQUAL = 70;
  public static final int CLOSEBRACKET = 82;
  public static final int PLUS = 56;
  public static final int NOT_EQUALS = 72;
  public static final int RW_BEGIN = 4;
  public static final int GREATEREQUAL = 71;
  public static final int RW_CHAR = 41;
  public static final int DECIMAL = 54;
  public static final int CHAR = 55;
  public static final int RW_RECORD = 27;
  public static final int GREATER = 69;
  public static final int RW_ELSE = 10;
  public static final int RW_IN = 17;
  public static final int RW_OR = 23;
  public static final int ASTERISK = 61;
  public static final int DOT = 83;
  public static final int OPENBRACE = 59;
  public static final int RW_SET = 29;
  public static final int RW_IF = 16;
  public static final int RW_DOWNTO = 9;
  public static final int RW_FUNCTION = 14;
  public static final int SEMICOLON = 80;
  public static final int NEGATION = 65;
  public static final int EOF = 0;
  public static final int RW_OF = 22;
  public static final int RW_END = 11;
  public static final int UNDERSCORE = 84;
  public static final int RW_CONST = 6;
  public static final int MINUS = 57;
  public static final int OPENBRACKET = 81;
  public static final int RW_PROCEDURE = 25;
  public static final int RW_CONTINUE = 47;
  public static final int RW_UNTIL = 33;
  public static final int OR = 76;
  public static final int error = 1;
  public static final int CLOSEPAR = 75;
  public static final int RW_READLN = 49;
  public static final int RW_INTEGER = 39;
  public static final int RW_TO = 31;
  public static final int RW_AND = 2;
  public static final int ID = 52;
  public static final int COLON = 66;
  public static final int RW_OR_ELSE = 45;
  public static final int RW_FILE = 12;
  public static final int RW_CASE = 5;
  public static final int RW_REPEAT = 28;
  public static final int RW_FALSE = 38;
  public static final int RW_ARRAY = 3;
  public static final int STRING = 51;
  public static final int LESS = 68;
  public static final int AND = 77;
  public static final int OPENPAR = 74;
  public static final int RW_WITH = 36;
  public static final int EQUALS = 58;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_AND",
  "RW_ARRAY",
  "RW_BEGIN",
  "RW_CASE",
  "RW_CONST",
  "RW_DIV",
  "RW_DO",
  "RW_DOWNTO",
  "RW_ELSE",
  "RW_END",
  "RW_FILE",
  "RW_FOR",
  "RW_FUNCTION",
  "RW_GOTO",
  "RW_IF",
  "RW_IN",
  "RW_LABEL",
  "RW_MOD",
  "RW_NIL",
  "RW_NOT",
  "RW_OF",
  "RW_OR",
  "RW_PACKED",
  "RW_PROCEDURE",
  "RW_PROGRAM",
  "RW_RECORD",
  "RW_REPEAT",
  "RW_SET",
  "RW_THEN",
  "RW_TO",
  "RW_TYPE",
  "RW_UNTIL",
  "RW_VAR",
  "RW_WHILE",
  "RW_WITH",
  "RW_TRUE",
  "RW_FALSE",
  "RW_INTEGER",
  "RW_REAL",
  "RW_CHAR",
  "RW_STRING",
  "RW_BOOLEAN",
  "RW_AND_THEN",
  "RW_OR_ELSE",
  "RW_BREAK",
  "RW_CONTINUE",
  "RW_WRITELN",
  "RW_READLN",
  "UNIT_MINUS",
  "STRING",
  "ID",
  "INTEGER",
  "DECIMAL",
  "CHAR",
  "PLUS",
  "MINUS",
  "EQUALS",
  "OPENBRACE",
  "CLOSEBRACE",
  "ASTERISK",
  "SLASH",
  "MODULO",
  "DOUBLEASTERISK",
  "NEGATION",
  "COLON",
  "DOUBLEEQUALS",
  "LESS",
  "GREATER",
  "LESSEQUAL",
  "GREATEREQUAL",
  "NOT_EQUALS",
  "LTGT",
  "OPENPAR",
  "CLOSEPAR",
  "OR",
  "AND",
  "NOT",
  "COMMA",
  "SEMICOLON",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "DOT",
  "UNDERSCORE",
  "ARROW"
  };
}

