package edu.robertob.p1compi2.view;

import edu.robertob.p1compi2.analysis.PLexer;
import edu.robertob.p1compi2.analysis.PParser;
import edu.robertob.p1compi2.data.CurrentSession;
import edu.robertob.p1compi2.data.PFile;
import edu.robertob.p1compi2.engine.base.Statement;
import edu.robertob.p1compi2.engine.statements.ConstantDeclaration;
import edu.robertob.p1compi2.engine.statements.TypeDeclaration;
import edu.robertob.p1compi2.engine.statements.VariableDeclaration;
import edu.robertob.p1compi2.engine.structs.*;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.LinkedList;

/**
 * @author robertob
 */
public class MainFrame extends JFrame {

    CurrentSession currentSession = new CurrentSession();
    TypesReportFrame typesReportFrame = new TypesReportFrame();
//    SymbolsReportFrame symbolsReportFrame = new SymbolsReportFrame();
//    ErrorsReportFrame errorsReportFrame = new ErrorsReportFrame();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        jToolBar2.setFloatable(false);
        jToolBar2.setLayout(new FlowLayout(FlowLayout.LEADING, 10, 5));

        consoleOutputLabel.setFont(consoleOutputLabel.getFont().deriveFont(Font.BOLD));

        jTextPane1.setFont(new Font("monospaced", Font.PLAIN, 14));
        jSplitPane2.setDividerLocation(0.5);
        jSplitPane2.setResizeWeight(0.5);

        // create a keyboard shortcut listener for the run button (ctrl+R, ctrl+ENTER)
        runCodeBtn.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_R, InputEvent.CTRL_DOWN_MASK), "runCode");
        runCodeBtn.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, InputEvent.CTRL_DOWN_MASK), "runCode");

        runCodeBtn.getActionMap().put("runCode", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
            if (currentSession.getActiveFileIndex() != -1)
                runCodeBtn.doClick();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new JToolBar();
        newFileBtn = new JButton();
        openFileBtn = new JButton();
        saveFileBtn = new JButton();
        saveAsFileBtn = new JButton();
        jSeparator2 = new JToolBar.Separator();
        fileStatusLabel = new JLabel();
        runCodeBtn = new JButton();
        analyzeAllCodeBtn = new JButton();
        jSplitPane2 = new JSplitPane();
        jPanel1 = new JPanel();
        jTabbedPane1 = new JTabbedPane();
        jPanel2 = new JPanel();
        consoleOutputLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextPane1 = new JTextPane();
        jMenuBar1 = new JMenuBar();
        reportsMenu = new JMenu();
        errorsMenuItem = new JMenuItem();
        jMenuItem2 = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(252, 252, 252));

        jToolBar2.setBackground(new Color(255, 255, 255));
        jToolBar2.setBorderPainted(false);
        jToolBar2.setEnabled(false);

        newFileBtn.setIcon(new ImageIcon(getClass().getResource("/file-plus.png"))); // NOI18N
        newFileBtn.setText("Nuevo archivo");
        newFileBtn.setFocusable(false);
        newFileBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        newFileBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        newFileBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newFileBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(newFileBtn);

        openFileBtn.setIcon(new ImageIcon(getClass().getResource("/file-import.png"))); // NOI18N
        openFileBtn.setText("Abrir archivo");
        openFileBtn.setFocusable(false);
        openFileBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        openFileBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        openFileBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                openFileBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(openFileBtn);

        saveFileBtn.setIcon(new ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        saveFileBtn.setText("Guardar");
        saveFileBtn.setEnabled(false);
        saveFileBtn.setFocusable(false);
        saveFileBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        saveFileBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        saveFileBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveFileBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(saveFileBtn);

        saveAsFileBtn.setIcon(new ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        saveAsFileBtn.setText("Guardar como...");
        saveAsFileBtn.setEnabled(false);
        saveAsFileBtn.setFocusable(false);
        saveAsFileBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        saveAsFileBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        saveAsFileBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveAsFileBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(saveAsFileBtn);

        jSeparator2.setBackground(new Color(204, 204, 204));
        jSeparator2.setForeground(new Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        jSeparator2.setSeparatorSize(new Dimension(1, 30));
        jToolBar2.add(jSeparator2);
        jToolBar2.add(fileStatusLabel);

        runCodeBtn.setIcon(new ImageIcon(getClass().getResource("/player-play.png"))); // NOI18N
        runCodeBtn.setText("Ejecutar");
        runCodeBtn.setEnabled(false);
        runCodeBtn.setFocusable(false);
        runCodeBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        runCodeBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        runCodeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                runCodeBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(runCodeBtn);

        analyzeAllCodeBtn.setIcon(new ImageIcon(getClass().getResource("/player-next.png"))); // NOI18N
        analyzeAllCodeBtn.setText("Analizar todos");
        analyzeAllCodeBtn.setEnabled(false);
        analyzeAllCodeBtn.setFocusable(false);
        analyzeAllCodeBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        analyzeAllCodeBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        analyzeAllCodeBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                analyzeAllCodeBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(analyzeAllCodeBtn);

        jSplitPane2.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTabbedPane1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel1);

        consoleOutputLabel.setText("Salida de la consola");

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleOutputLabel)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleOutputLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        jMenuBar1.setBackground(new Color(252, 252, 252));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new Font("Helvetica Neue", 0, 15)); // NOI18N

        reportsMenu.setText("Reportes");
        reportsMenu.setEnabled(false);

        errorsMenuItem.setIcon(new ImageIcon(getClass().getResource("/file-sad.png"))); // NOI18N
        errorsMenuItem.setText("Ver errores");
        errorsMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
//                errorsMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(errorsMenuItem);

        jMenuItem2.setIcon(new ImageIcon(getClass().getResource("/file-code.png"))); // NOI18N
        jMenuItem2.setText("Ver tabla de simbolos");
        jMenuItem2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        reportsMenu.add(jMenuItem2);

        jMenuBar1.add(reportsMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
            .addComponent(jToolBar2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane2, GroupLayout.Alignment.LEADING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newFileBtnActionPerformed
        var name = JOptionPane.showInputDialog(this, "Nombre del archivo");
        if (name == null || name.isEmpty()) {
            return;
        }
        var content = "";
        var sessionFile = new PFile(name, "", content, false, true, jTabbedPane1.getTabCount());
        currentSession.addFile(sessionFile);

        var textPane = new JTextPane();
        textPane.setText(content);
        var scrollPane = new JScrollPane(textPane, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        var tln = new TextLineNumber(textPane, 3);
        scrollPane.setRowHeaderView(tln);

//        textPane.setFont(new Font("monospacedd", Font.PLAIN, 15));
        textPane.setFont(new Font("monospaced", Font.PLAIN, 15));

        jTabbedPane1.add(name, scrollPane);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.getTabCount() - 1, new ButtonTabComponent(jTabbedPane1, currentSession));
        fileStatusLabel.setText("Modificado");
        fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.BOLD));
//        switchTabAndSetDocumentListener(sessionFile, textPane);
        switchTabAndSetDocumentListener(sessionFile, textPane);
    }//GEN-LAST:event_newFileBtnActionPerformed

    private void switchTabAndSetDocumentListener( PFile sessionFile, JTextPane textArea) {
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
        final String UNDO_ACTION = "Undo";
        final String REDO_ACTION = "Redo";

        final var undoMgr = new UndoManager();

        // Add listener for undoable events
        textArea.getDocument().addUndoableEditListener(new UndoableEditListener() {
            public void undoableEditHappened(UndoableEditEvent pEvt) {
                undoMgr.addEdit(pEvt.getEdit());
            }
        });

        // Add undo/redo actions
        textArea.getActionMap().put(UNDO_ACTION, new AbstractAction(UNDO_ACTION) {
            public void actionPerformed(ActionEvent pEvt) {
                try {
                    if (undoMgr.canUndo()) {
                        undoMgr.undo();
                    }
                } catch (CannotUndoException e) {
                    e.printStackTrace();
                }
            }
        });
        textArea.getActionMap().put(REDO_ACTION, new AbstractAction(REDO_ACTION) {
            public void actionPerformed(ActionEvent pEvt) {
                try {
                    if (undoMgr.canRedo()) {
                        undoMgr.redo();
                    }
                } catch (CannotRedoException e) {
                    e.printStackTrace();
                }
            }
        });

        // Create keyboard accelerators for undo/redo actions (Ctrl+Z/Ctrl+Y)
        textArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_Z, InputEvent.CTRL_DOWN_MASK),
                UNDO_ACTION);
        textArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_Y, InputEvent.CTRL_DOWN_MASK),
                REDO_ACTION);

        // using 'meta' for mac
        textArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_Z, InputEvent.META_DOWN_MASK),
                UNDO_ACTION);
        textArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_Y, InputEvent.META_DOWN_MASK),
                REDO_ACTION);


        textArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                sessionFile.setContent(textArea.getText());

                if (sessionFile.isSaved()) {
                    sessionFile.setSaved(false);
                    MainFrame.this.jTabbedPane1.setTitleAt(sessionFile.getIndex(), "*" + sessionFile.getName());

                    MainFrame.this.fileStatusLabel.setText("Modificado");
                    MainFrame.this.fileStatusLabel.setFont(MainFrame.this.fileStatusLabel.getFont().deriveFont(Font.BOLD));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                sessionFile.setContent(textArea.getText());

                if (sessionFile.isSaved()) {
                    sessionFile.setSaved(false);
                    MainFrame.this.jTabbedPane1.setTitleAt(sessionFile.getIndex(), "*" + sessionFile.getName());

                    MainFrame.this.fileStatusLabel.setText("Modificado");
                    MainFrame.this.fileStatusLabel.setFont(MainFrame.this.fileStatusLabel.getFont().deriveFont(Font.BOLD));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }

    private void openFileBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_openFileBtnActionPerformed
        var fileChooser = new JFileChooser();
        var result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            var file = fileChooser.getSelectedFile();
            var path = file.getAbsolutePath();
            var name = file.getName();
            var content = "";
            var sessionFile = new  PFile(name, path, content, true, false, jTabbedPane1.getTabCount());

            for (int i = 0; i < currentSession.getFiles().size(); i++) {
                if (currentSession.getFiles().get(i) != null && currentSession.getFiles().get(i).getSystemPath().equals(path)) {
                    JOptionPane.showMessageDialog(this, "El archivo ya está abierto", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            currentSession.addFile(sessionFile);

            try {
                var reader = new BufferedReader(new FileReader(path));
                var line = reader.readLine();
                while (line != null) {
                    content += line + "\n";
                    line = reader.readLine();
                }
                if (content.length() > 0) content = content.substring(0, content.length() - 1);
                sessionFile.setContent(content);
                reader.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
            var undoManager = new UndoManager();
            var textPane = new JTextPane();
            textPane.setText(content);
            var scrollPane = new JScrollPane(textPane, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            var tln = new TextLineNumber(textPane, 3);
            scrollPane.setRowHeaderView(tln);

            textPane.setFont(new Font("monospaced", Font.PLAIN, 15));

            jTabbedPane1.add(name, scrollPane);
            jTabbedPane1.setTabComponentAt(jTabbedPane1.getTabCount() - 1, new ButtonTabComponent(jTabbedPane1, currentSession));
            currentSession.setActiveFile(jTabbedPane1.getTabCount() - 1);
            switchTabAndSetDocumentListener(sessionFile, textPane);
        }


    }//GEN-LAST:event_openFileBtnActionPerformed

    private void jTabbedPane1StateChanged(ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // change the active file
        var index = jTabbedPane1.getSelectedIndex();
        if (index == -1) {
            fileStatusLabel.setText("");
            jTextPane1.setText("");
            saveFileBtn.setEnabled(false);
            saveAsFileBtn.setEnabled(false);
            runCodeBtn.setEnabled(false);
            analyzeAllCodeBtn.setEnabled(false);
            reportsMenu.setEnabled(false);
            return;
        }
        currentSession.setActiveFile(jTabbedPane1.getSelectedIndex());
        jTextPane1.setText(currentSession.getActiveFile().getConsoleOutput());
        if (currentSession.getActiveFile().isSaved()) {
            fileStatusLabel.setText("Guardado");
            fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.PLAIN));
            jTabbedPane1.setTitleAt(currentSession.getActiveFileIndex(), currentSession.getActiveFile().getName());
        } else {
            fileStatusLabel.setText("Modificado");
            fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.BOLD));
            jTabbedPane1.setTitleAt(currentSession.getActiveFileIndex(), "*" + currentSession.getActiveFile().getName());
        }
        saveFileBtn.setEnabled(true);
        saveAsFileBtn.setEnabled(true);
        runCodeBtn.setEnabled(true);
        analyzeAllCodeBtn.setEnabled(true);
        reportsMenu.setEnabled(true);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void saveFileBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveFileBtnActionPerformed
        var activeFile = currentSession.getActiveFile();
        if (activeFile != null) {
            if (!activeFile.isNew()) {
                activeFile.setSaved(true);
                activeFile.saveFile(activeFile.getContent(), false);
                fileStatusLabel.setText("Guardado");
                jTabbedPane1.setTitleAt(currentSession.getActiveFileIndex(), activeFile.getName());
                fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.PLAIN));
            } else {
                var fileChooser = new JFileChooser();
                fileChooser.setSelectedFile(new File(activeFile.getName() + ".p"));
                var result = fileChooser.showSaveDialog(this);
                // also set the default file name to the current file name
                if (result == JFileChooser.APPROVE_OPTION) {
                    var file = fileChooser.getSelectedFile();
                    var path = file.getAbsolutePath();
                    activeFile.setSystemPath(path);
                    activeFile.setIsNew(false);
                    activeFile.setSaved(true);
                    boolean created = activeFile.saveFile(activeFile.getContent(), true);
                    if (!created) return;
                    fileStatusLabel.setText("Guardado");
                    fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.PLAIN));
                    jTabbedPane1.setTitleAt(currentSession.getActiveFileIndex(), file.getName());
                }
            }
        }
    }//GEN-LAST:event_saveFileBtnActionPerformed

    private void runCodeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_runCodeBtnActionPerformed
        var code = currentSession.getActiveFile().getContent();
        code = code.trim();
        PLexer lexer = new PLexer(new StringReader(code));
        PParser parser = new PParser(lexer);
        currentSession.getActiveFile().getErrors().clear();
        LinkedList<PError> allErrors = new LinkedList<>();

        // Create the tables (types, symbols)

        try {
            var parserResult = parser.parse();
            TypesTable typesTable = new TypesTable("Global");
            typesTable.fillDefaultTypes();
            var tree = new Tree(((Program) parserResult.value).getAllStatements());
            allErrors = tree.getErrors();
            var globalTable = new SymbolTable("Global");
            tree.setGlobalTable(globalTable);
            currentSession.getActiveFile().setCurrentTree(tree);
            currentSession.getActiveFile().setGlobalTable(globalTable);
            currentSession.getActiveFile().setTypesTable(typesTable);

            //todo: 3 passes through the tree (when methods are implemented):
            // 1. get all the functions and their parameters, also structs
            // 2. get all the variables and their types
            // 3. execute the body of the main block

            for (Statement statement : tree.getStatements()) {
                if (statement == null) continue;

                if (statement instanceof TypeDeclaration || statement instanceof ConstantDeclaration || statement instanceof VariableDeclaration) {
                    var result = statement.execute(tree, globalTable, typesTable);
//                    if (result instanceof PError) {
//                        allErrors.add((PError) result);
//                    }
                }
            }

            //
            for (Statement statement : tree.getStatements()){
                if (statement == null) continue;
                if (!(statement instanceof TypeDeclaration || statement instanceof ConstantDeclaration || statement instanceof VariableDeclaration)) {
                    var result = statement.execute(tree, globalTable, typesTable);
//                    if (result instanceof PError) {
//                        allErrors.add((PError) result);
//                    }
                }
            }

            var alltypes = typesTable.collectAllEntries();
            for (var type : alltypes) {
                System.out.println(type.toString());
            }

        } catch (Exception e) {
            allErrors.add(new PError("Sintáctico", "Error al analizar el código", 0, 0));
            e.printStackTrace();
        }
        jTextPane1.setText("");
        allErrors.addAll(lexer.getLexicalErrorList());
        currentSession.getActiveFile().getErrors().addAll(lexer.getLexicalErrorList());
        allErrors.addAll(parser.getSyntaxErrorList());
        currentSession.getActiveFile().getErrors().addAll(parser.getSyntaxErrorList());
        if (allErrors.isEmpty()) {
            jTextPane1.setText(jTextPane1.getText() + "\n✅ -> Analisis completado sin errores\n");
        } else {
            jTextPane1.setText(jTextPane1.getText() + "\n❌ -> Análisis no fue exitoso - Errores encontrados:\n");
            for (PError error : allErrors) {
                jTextPane1.setText(jTextPane1.getText() + error.toString() + "\n");
            }
        }
        currentSession.getActiveFile().setConsoleOutput(jTextPane1.getText());
    }//GEN-LAST:event_runCodeBtnActionPerformed

//    private void errorsMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_errorsMenuItemActionPerformed
//        var activeFile = currentSession.getActiveFile();
//        if (activeFile != null) {
//            errorsReportFrame.setErrorsAndShow(activeFile.getErrors());
//        }
//    }//GEN-LAST:event_errorsMenuItemActionPerformed
//
    private void jMenuItem2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        var activeFile = currentSession.getActiveFile();
        if (activeFile != null) {
//            activeFile.getGlobalTable().addMethods(currentSession.getActiveFile().getCurrentTree());
            typesReportFrame.setTypesTableAndShow(activeFile.getTypesTable());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void saveAsFileBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveAsFileBtnActionPerformed
        var activeFile = currentSession.getActiveFile();
        if (activeFile != null) {
            if (!activeFile.isNew()) {
                var fileChooser = new JFileChooser();
                fileChooser.setSelectedFile(new File(activeFile.getName()));
                var result = fileChooser.showSaveDialog(this);

                if (result == JFileChooser.APPROVE_OPTION) {
                    var file = fileChooser.getSelectedFile();
                    var path = file.getAbsolutePath();
                    var newSessionFile = new PFile(file.getName(), path, activeFile.getContent(), true, false, jTabbedPane1.getTabCount());
                    boolean saved = newSessionFile.saveFile(newSessionFile.getContent(), true);
                    if (!saved) return;
                    currentSession.addFile(newSessionFile);

                    try {
                        var reader = new BufferedReader(new FileReader(path));
                        var line = reader.readLine();
                        var content = "";
                        while (line != null) {
                            content += line + "\n";
                            line = reader.readLine();
                        }
                        if (content.length() > 0) content = content.substring(0, content.length() - 1);
                        newSessionFile.setContent(content);
                        reader.close();
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }

                    var textPane = new JTextPane();
                    textPane.setText(newSessionFile.getContent());
                    var scrollPane = new JScrollPane(textPane, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                    var tln = new TextLineNumber(textPane, 3);
                    scrollPane.setRowHeaderView(tln);

                    textPane.setFont(new Font("monospaced", Font.PLAIN, 15));

                    jTabbedPane1.add(newSessionFile.getName(), scrollPane);
                    jTabbedPane1.setTabComponentAt(jTabbedPane1.getTabCount() - 1, new ButtonTabComponent(jTabbedPane1, currentSession));
                    currentSession.setActiveFile(jTabbedPane1.getTabCount() - 1);
                    switchTabAndSetDocumentListener(newSessionFile, textPane);
                }
            } else {
                var fileChooser = new JFileChooser();
                fileChooser.setSelectedFile(new File(activeFile.getName() + ".p"));
                var result = fileChooser.showSaveDialog(this);
                // also set the default file name to the current file name
                if (result == JFileChooser.APPROVE_OPTION) {
                    var file = fileChooser.getSelectedFile();
                    var path = file.getAbsolutePath();
                    activeFile.setSystemPath(path);
                    activeFile.setIsNew(false);
                    activeFile.setSaved(true);
                    boolean created = activeFile.saveFile(activeFile.getContent(), true);
                    if (!created) return;
                    fileStatusLabel.setText("Guardado");
                    fileStatusLabel.setFont(fileStatusLabel.getFont().deriveFont(Font.PLAIN));
                    jTabbedPane1.setTitleAt(currentSession.getActiveFileIndex(), file.getName());
                }
            }
        }
    }//GEN-LAST:event_saveAsFileBtnActionPerformed

    private void analyzeAllCodeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_analyzeAllCodeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzeAllCodeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton analyzeAllCodeBtn;
    private JLabel consoleOutputLabel;
    private JMenuItem errorsMenuItem;
    private JLabel fileStatusLabel;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItem2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JToolBar.Separator jSeparator2;
    private JSplitPane jSplitPane2;
    private JTabbedPane jTabbedPane1;
    private JTextPane jTextPane1;
    private JToolBar jToolBar2;
    private JButton newFileBtn;
    private JButton openFileBtn;
    private JMenu reportsMenu;
    private JButton runCodeBtn;
    private JButton saveAsFileBtn;
    private JButton saveFileBtn;
    // End of variables declaration//GEN-END:variables
}
